#!/bin/bash

# Define command-line arguments
NAMESPACE=$1
RESOURCE_TYPE=$2
RESOURCE_NAME=$3

# Function to print section headers
print_section_header() {
    echo -e "\n\e[1m$1\e[0m"
}

# Function to display resource information (pod or node)
display_resource_info() {
    local namespace=$1
    local resource_type=$2
    local resource_name=$3

    print_section_header "Resource Information - $resource_type in Namespace: $namespace"

    echo "${header[*]}" | column -t

    kubectl top $resource_type $resource_name --namespace="$namespace" | while read -r resource
    do
        NAME=$(echo "$resource" | awk '{print $1}')
        CPU_USAGE=$(echo "$resource" | awk '{print $2}')
        MEMORY_USAGE=$(echo "$resource" | awk '{print $3}')
        echo "$resource_type $namespace $NAME $CPU_USAGE $MEMORY_USAGE" | column -t
    done | column -t
}

# Check if namespace and resource type are provided as parameters
if [ $# -lt 2 ]; then
    echo "Usage: $0 <namespace> <resource-type> <resource-name>"
    exit 1
fi

# Execute the function to display resource information
display_resource_info "$NAMESPACE" "$RESOURCE_TYPE" "$RESOURCE_NAME"
